name: Build and Verify

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: build
        run: bundle exec jekyll build

      - name: check output
        run: |
          bundle exec htmlproofer ./_site \
            --allow-hash-href \
            --check-html \
            --only-4xx \
            --disable-external \
            --empty-alt-ignore

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: toolbox-homepage-build
          path: ./_site

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: toolbox-homepage-build
          path: ./_site
          run-id: ${{ github.event.workflow_run.id }}

      - name: Test artifact
        run: |
          ls -a