name: Build and Verify
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build the website
        run: bundle exec jekyll build

      - name: Check the build
        run: |
          bundle exec htmlproofer ./_site \
            --allow-hash-href \
            --check-html \
            --only-4xx \
            --disable-external \
            --empty-alt-ignore