name: Build and deploy
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: vendor/bundle
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: latest

      - name: Install Jupyter Book
        run: npm install -g jupyter-book

      - name: Build site
        run: |
          bash build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: toolbox-homepage-build
          path: ./_site

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: toolbox-homepage-build
          path: ./_site

      - name: Upload to server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa "$DEPLOY_HOST" 2> /dev/null | sort -u  -o ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          chmod 600 ~/.ssh/deploy_key
          ssh-add ~/.ssh/deploy_key
          rsync -rq --links --delete --exclude=".*" ./_site/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"

