name: Upload
on:
  workflow_run:
    workflows: ["Build and Verify"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: install dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: build
        run: bundle exec jekyll build

      - name: Unpack artifact
        run: |
          tar -xvf ./_site/artifact.tar -C ./_site/
          rm -rf ./_site/artifact.tar

      - name: Upload to server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa "$DEPLOY_HOST" 2> /dev/null | sort -u  -o ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          chmod 600 ~/.ssh/deploy_key
          ssh-add ~/.ssh/deploy_key
          rsync -rq --links --delete --exclude=".*" ./_site/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"