name: Upload
on:
  workflow_run:
    workflows: ["Build and Verify"]
    branches: [main, _artifact_versions]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: toolbox-homepage-build
          path: ./_site
          github-token: ${{ secrets.GH_ARTIFACT_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
